name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report

        Thanks for taking the time to report a bug! This helps us improve Pragmatic UX Design.

        **Before submitting:**
        - [ ] I have searched for similar issues
        - [ ] I have tested with the latest version
        - [ ] I have checked the documentation

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome/Chromium
        - Firefox
        - Safari
        - Edge
        - Opera
        - Mobile Safari (iOS)
        - Chrome Mobile (Android)
        - Other (please specify)
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: Which version of the browser are you using? (e.g., 120.0.6099.109)
      placeholder: "120.0.6099.109"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
        - Other (please specify)
    validations:
      required: true

  - type: input
    id: reproduction-url
    attributes:
      label: Reproduction URL
      description: If applicable, provide a URL where the bug can be reproduced
      placeholder: "https://pragmaticux.design/decision-helper"

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Describe the bug clearly and concisely
      placeholder: "When I click the 'Get Results' button, nothing happens..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide step-by-step instructions to reproduce the bug
      placeholder: |
        1. Go to '/decision-helper'
        2. Answer all questions
        3. Click 'Get Results'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: "The results should display with recommended principles and methods"

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "Nothing happens, or an error is displayed"

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain the problem
      placeholder: "Drag and drop images here"

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem
      placeholder: "Console errors, network requests, etc."

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have provided all the information requested above
          required: true
        - label: I understand this is a bug report, not a feature request
