name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request

        Thanks for suggesting a new feature! Your ideas help shape the future of Pragmatic UX Design.

        **Before submitting:**
        - [ ] I have searched for similar feature requests
        - [ ] This feature would benefit other users
        - [ ] I understand this is a suggestion, not a guarantee

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: Provide a brief summary of the feature you'd like to see
      placeholder: "Add a dark mode toggle to the website"
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem would this feature solve?
      placeholder: "Users who work in low-light environments struggle to read content comfortably"
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: "Add a toggle button in the header that switches between light and dark themes, with the preference saved in localStorage"
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: "Using system preference detection, or a separate dark mode subdomain"

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my workflow
        - Critical/blocking my work
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (CSS/styling changes)
        - Medium (new components/functionality)
        - Complex (architectural changes)
        - Very Complex (major rewrite)

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples
      placeholder: "Links to similar implementations, user research, etc."

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have provided all the information requested above
          required: true
        - label: I understand this is a feature request, not a bug report
